import type { HintRecord } from '../types';
import { formatStatus } from '../format';

interface HintStackProps {
  hints: HintRecord[];
  runtimeConfigured?: boolean;
}

export function HintStack({ hints, runtimeConfigured }: HintStackProps) {
  const hasHeuristicFallback = hints.some((h) => h.source === 'heuristic');

  return (
    <div className="hint-stack">
      <h3>Hints shown</h3>
      {hasHeuristicFallback && (
        <div className="hint-fallback-warning" style={{ padding: '0.75rem', borderRadius: '0.375rem', marginBottom: '1rem', border: '1px solid var(--border-color)', backgroundColor: 'var(--bg-card)', fontSize: '0.875rem' }}>
          <strong style={{ display: 'block', marginBottom: '0.25rem', color: '#eab308' }}>
            ⚠️ {runtimeConfigured ? 'AI runtime unavailable' : 'AI not configured'}
          </strong>
          <span style={{ color: 'var(--text-secondary)' }}>
            These hints were generated by basic local wordplay heuristics.{' '}
            {runtimeConfigured ? (
              <>The backend has <code>CROSSWORD_RUNTIME_COMMAND</code> set, but the runtime call did not succeed (check backend logs).</>
            ) : (
              <>Configure <code>CROSSWORD_RUNTIME_COMMAND</code> on the backend to enable the LLM agent runtime.</>
            )}
          </span>
        </div>
      )}
      {hints.length ? (
        hints.map((hint) => (
          <article key={`${hint.level}-${hint.kind}`} className="hint-card">
            <div className="hint-card-header">
              <span className="hint-level">Level {hint.level}</span>
              <span className="hint-kind">{formatStatus(hint.kind)}</span>
            </div>
            <p>{hint.text}</p>
          </article>
        ))
      ) : (
        <p className="hint-empty">No hints revealed yet.</p>
      )}
    </div>
  );
}
